export const SITE_URL = "https://www.indyanabalasse.com";
export const SITE_NAME = "INDYANASTUDIO";
export const CONTACT_EMAIL = "indyana.balasse@gmail.com";
export const CONTACT_PHONE_DISPLAY = "+32 484 24 22 23";
export const CONTACT_PHONE_HREF = "+32484242223";
export const CONTACT_ADDRESS = "143 rue du Ham, 1180 Uccle, Belgique";
export const CONTACT_MAPS_URL = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(CONTACT_ADDRESS)}`;
export const CONTACT_STREET = "143 rue du Ham";
export const CONTACT_CITY = "Uccle";
export const CONTACT_POSTAL_CODE = "1180";
export const CONTACT_COUNTRY = "BE";
export const INSTAGRAM_HANDLE = "@indyanastudio";
export const INSTAGRAM_URL = "https://www.instagram.com/indyanastudio";
